### ISSUE TITLE
VIA Conversion Issue

### ISSUE THREAD

**Issue by Yasas4D** [rubetek/rubetools#3]
First of all, I would like to thank rubetek team for providing such a good tool.
I have found a little issue with your VIA conversation code. (rubetools/formats/via.py)
I think the original format is quite different or updated. Here is the new format

![yasas1](https://user-images.githubusercontent.com/49401137/126114729-ded698e6-7e47-4091-9c78-bd4c669f1c99.png)

So the metadata field needs to be removed from your code as shown below.

![yasas](https://user-images.githubusercontent.com/49401137/126114861-8bdd2382-d9e6-4fd8-b3db-b0120e6124ea.png)

Hope you will improve it further.
Thank you.

**Comment by lukseny** [comment]
@Yasas4D Thank you for the issue
If you wish you can make a pull request and help us to improve the code
We would be grateful for any other tips and comments on advancing our tool and making it more useful!

**Comment by Yasas4D** [comment]
Sure @lukseny  It is a great honor and pleasure for me to contribute to such a great project.

**Comment by denisfin** [comment]
done in pull_request
